const data = [
  {
    album: {
      album_type: 'single',
      artists: [
        {
          external_urls: { spotify: 'https://open.spotify.com/artist/5yG7ZAZafVaAlMTeBybKAL' },
          href: 'https://api.spotify.com/v1/artists/5yG7ZAZafVaAlMTeBybKAL',
          id: '5yG7ZAZafVaAlMTeBybKAL',
          name: 'Iggy Azalea',
          type: 'artist',
          uri: 'spotify:artist:5yG7ZAZafVaAlMTeBybKAL',
        },
      ],
      available_markets: [
        'AD',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'EC',
        'EE',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IS',
        'IT',
        'JP',
        'LI',
        'LT',
        'LU',
        'LV',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'PA',
        'PE',
        'PH',
        'PL',
        'PT',
        'PY',
        'RO',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA',
      ],
      external_urls: { spotify: 'https://open.spotify.com/album/4n2l2LaTU83S2Wx5YVnYEG' },
      href: 'https://api.spotify.com/v1/albums/4n2l2LaTU83S2Wx5YVnYEG',
      id: '4n2l2LaTU83S2Wx5YVnYEG',
      images: [
        { height: 640, url: 'https://i.scdn.co/image/ca27a8bf6de4d8cab422dcd405e6434cdd2b7794', width: 640 },
        { height: 300, url: 'https://i.scdn.co/image/c6aa1ea577e389fbf357ac479d635ce8cdd71c50', width: 300 },
        { height: 64, url: 'https://i.scdn.co/image/1a84d0019b1b3869f849550bae171e576b5882c6', width: 64 },
      ],
      name: 'Savior',
      release_date: '2018-02-02',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:4n2l2LaTU83S2Wx5YVnYEG',
    },
    artists: [
      {
        external_urls: { spotify: 'https://open.spotify.com/artist/5yG7ZAZafVaAlMTeBybKAL' },
        href: 'https://api.spotify.com/v1/artists/5yG7ZAZafVaAlMTeBybKAL',
        id: '5yG7ZAZafVaAlMTeBybKAL',
        name: 'Iggy Azalea',
        type: 'artist',
        uri: 'spotify:artist:5yG7ZAZafVaAlMTeBybKAL',
      },
      {
        external_urls: { spotify: 'https://open.spotify.com/artist/0VRj0yCOv2FXJNP47XQnx5' },
        href: 'https://api.spotify.com/v1/artists/0VRj0yCOv2FXJNP47XQnx5',
        id: '0VRj0yCOv2FXJNP47XQnx5',
        name: 'Quavo',
        type: 'artist',
        uri: 'spotify:artist:0VRj0yCOv2FXJNP47XQnx5',
      },
    ],
    available_markets: [
      'AD',
      'AR',
      'AT',
      'AU',
      'BE',
      'BG',
      'BO',
      'BR',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'EC',
      'EE',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HU',
      'ID',
      'IE',
      'IL',
      'IS',
      'IT',
      'JP',
      'LI',
      'LT',
      'LU',
      'LV',
      'MC',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'PA',
      'PE',
      'PH',
      'PL',
      'PT',
      'PY',
      'RO',
      'SE',
      'SG',
      'SK',
      'SV',
      'TH',
      'TR',
      'TW',
      'US',
      'UY',
      'VN',
      'ZA',
    ],
    disc_number: 1,
    duration_ms: 211013,
    explicit: false,
    external_ids: { isrc: 'USUM71800771' },
    external_urls: { spotify: 'https://open.spotify.com/track/4HkjO6S6yYJr8uyFLBZyEf' },
    href: 'https://api.spotify.com/v1/tracks/4HkjO6S6yYJr8uyFLBZyEf',
    id: '4HkjO6S6yYJr8uyFLBZyEf',
    name: 'Savior',
    popularity: 70,
    preview_url: null,
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:4HkjO6S6yYJr8uyFLBZyEf',
  },
  {
    album: {
      album_type: 'single',
      artists: [
        {
          external_urls: { spotify: 'https://open.spotify.com/artist/3ubJycxLEy7j9MMwwEOHfp' },
          href: 'https://api.spotify.com/v1/artists/3ubJycxLEy7j9MMwwEOHfp',
          id: '3ubJycxLEy7j9MMwwEOHfp',
          name: '2018 Dynamo Hitz',
          type: 'artist',
          uri: 'spotify:artist:3ubJycxLEy7j9MMwwEOHfp',
        },
      ],
      available_markets: [
        'AD',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'EC',
        'EE',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IS',
        'IT',
        'JP',
        'LI',
        'LT',
        'LU',
        'LV',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'PA',
        'PE',
        'PH',
        'PL',
        'PT',
        'PY',
        'RO',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA',
      ],
      external_urls: { spotify: 'https://open.spotify.com/album/1hzfN06T5TSKD4nHzGcYzZ' },
      href: 'https://api.spotify.com/v1/albums/1hzfN06T5TSKD4nHzGcYzZ',
      id: '1hzfN06T5TSKD4nHzGcYzZ',
      images: [
        { height: 600, url: 'https://i.scdn.co/image/9834ca1d0f6100bce8cd1751165e38af1454abb3', width: 600 },
        { height: 300, url: 'https://i.scdn.co/image/e288abd1f914d05032dab65f679582aacb0de4f7', width: 300 },
        { height: 64, url: 'https://i.scdn.co/image/d6f50fb65ac4cf63c85baeb551eea473464ad366', width: 64 },
      ],
      name: 'Savior (Originally performed by Iggy Azalea and Quavo)',
      release_date: '2018-02-13',
      release_date_precision: 'day',
      type: 'album',
      uri: 'spotify:album:1hzfN06T5TSKD4nHzGcYzZ',
    },
    artists: [
      {
        external_urls: { spotify: 'https://open.spotify.com/artist/3ubJycxLEy7j9MMwwEOHfp' },
        href: 'https://api.spotify.com/v1/artists/3ubJycxLEy7j9MMwwEOHfp',
        id: '3ubJycxLEy7j9MMwwEOHfp',
        name: '2018 Dynamo Hitz',
        type: 'artist',
        uri: 'spotify:artist:3ubJycxLEy7j9MMwwEOHfp',
      },
    ],
    available_markets: [
      'AD',
      'AR',
      'AT',
      'AU',
      'BE',
      'BG',
      'BO',
      'BR',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'EC',
      'EE',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HU',
      'ID',
      'IE',
      'IL',
      'IS',
      'IT',
      'JP',
      'LI',
      'LT',
      'LU',
      'LV',
      'MC',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'PA',
      'PE',
      'PH',
      'PL',
      'PT',
      'PY',
      'RO',
      'SE',
      'SG',
      'SK',
      'SV',
      'TH',
      'TR',
      'TW',
      'US',
      'UY',
      'VN',
      'ZA',
    ],
    disc_number: 1,
    duration_ms: 207203,
    explicit: false,
    external_ids: { isrc: 'GBJHM1870001' },
    external_urls: { spotify: 'https://open.spotify.com/track/39lCBkI5a26BnESgTkVdJZ' },
    href: 'https://api.spotify.com/v1/tracks/39lCBkI5a26BnESgTkVdJZ',
    id: '39lCBkI5a26BnESgTkVdJZ',
    name: 'Savior',
    popularity: 2,
    preview_url:
      'https://p.scdn.co/mp3-preview/87b37e9d1ae66ce76f904c100923872b8a0939d6?cid=afee75ea69ad48bfbdc676e023f9b814',
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:39lCBkI5a26BnESgTkVdJZ',
  },
];

export default data;
